### ISSUE TITLE
how is PartialServiceConfiguration class being used?

### ISSUE THREAD

**Issue by qinfchen** [palantir/http-remoting-api#32]
ClientConfiguration can be created using ServiceConfiguration and there is no easy way to convert PartialServiceConfiguration to ServiceConfiguration or vice versa even though they are pretty much identical except for the absence of `security`.  I would like know more about how we intend to use the PartialServiceConfiguration class

**Comment by qinfchen** [comment]
Can we make `ServiceConfigurationFactor.propagateDefaults` pubic?

**Comment by uschi2000** [comment]
What's the use-case for this?

**Comment by qinfchen** [comment]
Having a PartialServiceConfiguration declare outside the service discovery block like multipass'
```
auth:
  legacyModeEnabled: false
  multipass:
    security:
      trustStorePath: var/security/trustStore.jks
    uris:
    - https://multipass.palantir.dev:8643/multipass/api
```

or slate's postgate data source config
```
- dataSourcePoolCacheTimeout: 1m
  databaseName: palantir
  driver: org.postgresql.ds.PGSimpleDataSource
  maximumDataSourcePoolSize: 30
  name: Foundry
  portNumber: 5432
  postgate:
    uris: https://spp.palantir.dev:6473/postgate/api/
  serverName: postgres.palantir.dev
  type: foundry
```
It'd be great if we can specify service configuration outside of service discovery without requiring ssl block.  Unless we are encouraging teams to only take service configuration from service discovery?
